package initializationAndCleanup;

public class Ex3_testDefaultConstructor {

	public Ex3_testDefaultConstructor() {
		System.out.println("This text was generated by default constructor");
	}
	
}
