package initializationAndCleanup;

public class Ex4_testOverloadedConstructor {

	public Ex4_testOverloadedConstructor() {
		System.out.println("This text was generated by default constructor");
	}
	
	public Ex4_testOverloadedConstructor(String s) {
		System.out.println("This text was generated by overloaded constructor. " + s);
	}
}
